#!/bin/sh
sync

case "$1" in
	load)
		echo "Inserting DVB modules into kernel"
		# make sure input stuff is there for IR remote controls
		modprobe input
		modprobe evdev
		# vide4linux for av7110 based "full featured" cards
		modprobe videodev
		modprobe v4l1-compat
		modprobe v4l2-common
		modprobe video-buf
		# DVB core
		modprobe dvb-core
		# frontend drivers
		modprobe ves1x93
		modprobe alps_tdlb7
		modprobe alps_tdmb7
		modprobe stv0299
		modprobe ves1820
		modprobe tda1004x
		modprobe grundig_29504-401
		modprobe grundig_29504-491
		modprobe cx24110
		modprobe mt312	
		# saa7146 based siemens/technotrend/hauppauge cards
		modprobe saa7146
		modprobe saa7146_vv
		modprobe ttpci-eeprom
		modprobe dvb-ttpci
		modprobe budget-core
		modprobe budget
		modprobe budget-ci
		modprobe budget-av
		# technotrend/hauppauge USB things
		modprobe dvb-ttusb-budget
		modprobe ttusb_dec
		# technisat skystar2
		modprobe b2c2_flexcop_pci
		echo
		;;
	debug)
		echo "Inserting DVB modules (debug) into kernel"
		modprobe videodev
		modprobe input
		modprobe evdev
		modprobe v4l1-compat
		modprobe v4l2-common
		modprobe video-buf
		modprobe dvb-core
		modprobe ves1x93
		modprobe alps_tdlb7
		modprobe alps_tdmb7
		modprobe stv0299
		modprobe ves1820
		modprobe tda1004x
		modprobe grundig_29504-401
		modprobe grundig_29504-491
		modprobe cx24110
		modprobe saa7146
		modprobe saa7146_vv saa7146_debug=247
		modprobe ttpci-eeprom
		modprobe dvb-ttpci av7110_debug=247
		modprobe budget-core
		modprobe budget
		modprobe budget-ci
		modprobe budget-av
		modprobe dvb-ttusb-budget
		modprobe mt312
		modprobe b2c2_flexcop_pci debug=1
		modprobe ttusb_dec
		echo
		;;
	unload)
		echo "Deleting DVB modules from kernel"
		rmmod	b2c2_flexcop_pci b2c2_flexcop mt312 dvb-ttpci budget \
			budget-av budget-ci budget-core ttusb_dec \
			dvb-ttusb-budget ttpci-eeprom ves1x93 alps_tdmb7 \
			alps_tdlb7 stv0299 ves1820 tda1004x grundig_29504-401 \
			grundig_29504-491 cx24110 saa7146_vv saa7146 skystar2 \
			video-buf v4l2-common v4l1-compat dvb-core videodev \
			2> /dev/null
		echo
		;;
	reload)
		$0 unload && $0 load
		;;
	*)
		echo "Usage$0 {load|unload|debug|reload}"
		exit 1
esac

sync

